version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /src/app/node_modules
      - .:/src/app
    ports:
      - "3000:3000"
    environment:
      HOST: 0.0.0.0
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /src/app/node_modules
      - .:/src/app
    command: ["yarn", "test"]


